name: Setup-build-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

#------- Setup build, compile classes & packages, and upload artifact to GitHub Pages
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository, setup build environment and cleanup build folder
      - name: Checkout repository
        uses: actions/checkout@v4

    # Setup build directory
      - name: Clear and recreate the .build directory
        run:  |
          rm -rf ./.build
          mkdir -p ./.build

    # Drop home page files in the build
      - name: Drop home page files into the build
        run: |
          mkdir -p ./.build/res
          cp ./index.html ./index.css ./.build/
          cp -r ./res/* ./.build/res/

    # Drop VSCode setup guide in the build
      - name: Drop VSCode setup guide in the build
        run: |
          mkdir -p ./.build/VSCode
          cp -r ./VSCode/* ./.build/VSCode/

    # Create and upload build drop artifact
      - name: Create and upload build drop artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: build-drop
          path: ./.build/

#------- Deploy the generated build artifact to github-pages
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Deploy pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: build-drop
